"""Configuration for A2 Policy (ViLGP3D)."""
from dataclasses import dataclass, field
from typing import Optional

# Try to import from lerobot, fallback to standalone
try:
    from lerobot.configs.policies import PreTrainedConfig
    from lerobot.configs.types import NormalizationMode
    _HAS_LEROBOT = True
except ImportError:
    _HAS_LEROBOT = False

    class NormalizationMode:
        NONE = "none"


if _HAS_LEROBOT:
    @PreTrainedConfig.register_subclass("a2")
    @dataclass
    class A2Config(PreTrainedConfig):
        """Configuration class for A2Policy (ViLGP3D).

        This policy uses CLIP-based cross-attention for 6-DOF grasp and place
        pose selection from candidate actions generated by GraspNet/PlaceNet.
        """

        # Policy identification
        name: str = "a2"

        # Observation settings
        n_obs_steps: int = 1

        # Action settings
        action_dim: int = 7  # xyz (3) + quaternion (4)

        # Network architecture
        width: int = 768
        layers: int = 1
        heads: int = 8

        # Position encoding
        use_rope: bool = True
        no_feat_rope: bool = False

        # Point cloud processing
        sample_num: int = 500

        # Feature backbone
        feat_backbone: str = "clip"

        # Fusion settings
        fusion_sa: bool = False
        no_rgb_feat: bool = False

        # GraspNet checkpoint path
        graspnet_checkpoint: Optional[str] = None

        # Device
        device: Optional[str] = None

        # Normalization
        normalization_mode: NormalizationMode = NormalizationMode.NONE

        # Input/output features (will be set based on environment)
        input_features: dict = field(default_factory=dict)
        output_features: dict = field(default_factory=dict)

        def __post_init__(self):
            super().__post_init__()

        def validate_features(self) -> None:
            """Validate input/output feature compatibility."""
            pass
else:
    @dataclass
    class A2Config:
        """Configuration class for A2Policy (ViLGP3D) - standalone version.

        This policy uses CLIP-based cross-attention for 6-DOF grasp and place
        pose selection from candidate actions generated by GraspNet/PlaceNet.
        """

        # Policy identification
        name: str = "a2"

        # Observation settings
        n_obs_steps: int = 1

        # Action settings
        action_dim: int = 7  # xyz (3) + quaternion (4)

        # Network architecture
        width: int = 768
        layers: int = 1
        heads: int = 8

        # Position encoding
        use_rope: bool = True
        no_feat_rope: bool = False

        # Point cloud processing
        sample_num: int = 500

        # Feature backbone
        feat_backbone: str = "clip"

        # Fusion settings
        fusion_sa: bool = False
        no_rgb_feat: bool = False

        # GraspNet checkpoint path
        graspnet_checkpoint: Optional[str] = None

        # Device
        device: Optional[str] = None

        # Normalization
        normalization_mode: str = "none"

        # Input/output features (will be set based on environment)
        input_features: dict = field(default_factory=dict)
        output_features: dict = field(default_factory=dict)

        def validate_features(self) -> None:
            """Validate input/output feature compatibility."""
            pass
